name: PolizeiWache
version: '${project.version}'
main: de.titus.polizeiwache.Polizeiwache
api-version: 1.18
authors: [ Titus, Alex ]
description: PolizeiWache Challenge-Server Plugin
commands:
  gm:
    permission: core.gamemode

  fly:
    permission: core.fly

  utils:
    permission: core.utils
    aliases:
      - u

  vanish:
    permission: core.vanish
    aliases:
      - v

  discord:
    aliases:
      - dc

  commands:
    aliases:
      - cmd